## Setup

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.autograd import Variable
from torch.utils.data import DataLoader
from torch.utils.data import sampler

import torchvision.datasets as dset
import torchvision.transforms as T

import numpy as np

import timeit

In [2]:
from datetime import datetime
from FireSimulator import *
from FireSimulatorUtilities import *
import glob
import itertools
import matplotlib.patches as patches
import matplotlib.pyplot as plt
import os
import pickle
import time

%matplotlib inline
plt.rcParams['figure.figsize'] = (10.0, 8.0)
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

%load_ext autoreload
%autoreload 2

## Utility functions

In [3]:
class Flatten(nn.Module):
    def forward(self, x):
        N, C, H, w = x.size() 
        return x.view(N, -1)

In [4]:
def heuristic_trajectory(pos, center, num_actions, img_st, isfire):
    trajectory = []
    trajectory.append((pos[0],pos[1]))
    img_dim = img_st.shape[0]
    
    if isfire:
        fires_r, fires_c = np.where(img_st==1)
        neighbors = [(-1,0),(1,0),(0,1),(0,-1)]
        fire = []
        bdry = []
        for r,c in zip(fires_r,fires_c):
            counter = 0
            for (dr,dc) in neighbors:
                rn = r + dr
                cn = c + dc
                if rn>=0 and rn<img_dim and cn>=0 and cn<img_dim and img_st[rn,cn] == 0:
                    counter += 1
                    
            x = col_to_x(c) - img_dim//2 + pos[0]
            y = row_to_y(img_dim,r) - img_dim//2 + pos[1]
            if counter >= 2:
                bdry.append((x,y))
            else:
                fire.append((x,y))
                
        using_bdry = False
        if len(bdry) > 0:
            dists = [(np.abs(x-pos[0])+np.abs(y-pos[1]),(x,y)) for (x,y) in bdry]
            using_bdry = True
        else:
            dists = [(np.abs(x-pos[0])+np.abs(y-pos[1]),(x,y)) for (x,y) in fire]
            
        target = min(dists)[1]
        while len(trajectory) < num_actions+1:
            loc = trajectory[-1]
            if loc == target:
                if using_bdry:
                    bdry.remove(target)
                elif len(fire) > 0:
                    fire.remove(target)
                    
                using_bdry = False
                if len(bdry) > 0:
                    dists = [(np.abs(x-loc[0])+np.abs(y-loc[1]),(x,y)) for (x,y) in bdry]
                    target = min(dists)[1]
                    using_bdry = True
                elif len(fire) > 0:
                    dists = [(np.abs(x-loc[0])+np.abs(y-loc[1]),(x,y)) for (x,y) in fire]
                    target = min(dists)[1]
                else:
                    target = trajectory[-1]
                    
            dists = []
            for a in range(9):
                new_loc = actions_to_trajectory(trajectory[-1],[a])[1]
                dists.append((np.abs(new_loc[0]-target[0])+np.abs(new_loc[1]-target[1]),new_loc))
                
            trajectory.append(min(dists)[1])
            #print(trajectory)
        
    else:
        for k in range(num_actions):
            dists = []
            for a in range(9):
                new_loc = actions_to_trajectory(trajectory[-1],[a])[1]
                dists.append((np.abs(center-new_loc[0])+np.abs(center-new_loc[1]),new_loc))
            
            trajectory.append(min(dists)[1])
            
    return trajectory

## Load data

In [5]:
# directory = os.path.join(os.getcwd(), 'data')

# pattern = os.path.join(directory,'states_seed_*')

# data = {}
# k = 0
# total_states = 0
# for file in glob.glob(pattern):
#     fh = open(file, 'rb')
#     sub_data = pickle.load(fh)
#     data[k] = sub_data
#     fh.close()
#     k += 1
#     total_states += sub_data.shape[0]
    
# print('loaded %d sims from file' %(k))
# print('for a total of %d states' %(total_states))

## Network datatype [cpu/gpu]

In [6]:
torch.cuda.is_available()

True

In [7]:
# dtype = torch.FloatTensor
dtype = torch.cuda.FloatTensor

## Build the network

In [13]:
class eelfff_net(nn.Module):
    """
    network to approximate Q function
    """
    def __init__(self, act_seq=4, img_dim=8):
        self.act_seq = act_seq
        self.img_dim = img_dim
        self.num_poss_actions = 9
        
        C, H, W = 1, img_dim, img_dim
        hidden_dim = 2048
        
        # conv layer settings
        nf1 = 128; nf2 = 128
        fs1 = 2; fs2 = 2
        cv_s1 = 1; cv_s2 = 1
        cv_p1 = 0; cv_p2 = 0
        
        # pool layer settings
        p_sz1 = 4; p_sz2 = 2
        p_st1 = 1; p_st2 = 1
        
        # calculate affine layer size
        Hp1 = 1 + (H + 2*cv_p1 - fs1) // cv_s1
        Wp1 = Hp1
        Hpp1 = 1 + (Hp1 - p_sz1) // p_st1
        Wpp1 = Hpp1
        
        Hp2 = 1 + (Hpp1 + 2*cv_p2 - fs2) // cv_s2
        Wp2 = Hp2
        Hpp2 = 1 + (Hp2 - p_sz2) // p_st2
        Wpp2 = Hpp2
        
        #aff_flat_size = nf2*Hpp2*Wpp2 + 2*act_seq
        aff_flat_size = nf1*Hpp1*Wpp1 + 2*(act_seq+1) + 2
        
        super(eelfff_net, self).__init__()
        # cnn structure
        self.cnn = nn.Sequential(
                        nn.Conv2d(C, nf1, kernel_size=fs1, stride=cv_s1, padding=cv_p1),
                        nn.ReLU(inplace=True),
                        nn.MaxPool2d(p_sz1,stride=p_st1),
                        #nn.Conv2d(nf1, nf2, kernel_size=fs2, stride=cv_s2, padding=cv_p2),
                        #nn.ReLU(inplace=True),
                        #nn.MaxPool2d(p_sz2,stride=p_st2),
                        Flatten()
                    )
        
        # nonlinear structure
        self.aff = nn.Sequential(
                        nn.Linear(aff_flat_size, hidden_dim),
                        nn.ReLU(inplace=True),
                        nn.Linear(hidden_dim, self.num_poss_actions*act_seq)
                    )
        
    def forward(self, img, act, center):
        img_exp = img.unsqueeze(0)
        img_exp = img_exp.unsqueeze(0)
        act_exp = act.unsqueeze(0)
        cen_exp = center.unsqueeze(0)
        feat = self.cnn(img_exp)
        feat = torch.cat((feat, act_exp, cen_exp), dim=1)
        Q = self.aff(feat)
        
        return Q.view(N,self.num_poss_actions,self.act_seq)

test implementation of network with random data

In [14]:
tic = time.clock()
N = 1
img_dim = 8
act_seq = 6
model = eelfff_net(act_seq, img_dim).type(dtype)

img = torch.randn(img_dim,img_dim).type(dtype)
act = torch.randn(2*(act_seq+1)).type(dtype)
center = torch.randn(2).type(dtype)

img_var = Variable(img)
act_var = Variable(act)
center_var = Variable(center)

Q = model(img_var, act_var, center_var)
toc = time.clock()

print(Q.size())
print("%0.2fs = %0.2fm elapsed for this test" %(toc-tic,(toc-tic)/60))

torch.Size([1, 9, 6])
24.92s = 0.42m elapsed for this test


## Define a reward function

In [15]:
def eelfff_reward(states, trajs, fire_flags, other_trajs):
    N = len(states)
    grid_size = states[0].shape[0]
    center = math.ceil(grid_size/2)
    neighbors = [(-1,0),(0,-1),(1,0),(0,1)]
    #reward = Variable(torch.zeros(1), requires_grad=True).type(dtype)
    reward = 0
    
    for n in range(N):
        st = states[n]
        traj = trajs[n]
        other_traj = other_trajs[n]
        has_fires = fire_flags[n]
        
        # reward for treating fires and boundary fires
        # that weren't already treated by the agent
        if has_fires:
            treated = []
            for (x,y) in traj:
                r = y_to_row(grid_size,y)
                c = x_to_col(x)

                # reward for treating a fire
                if r>=0 and r<grid_size and c>=0 and c<grid_size and st[r,c] == 1 and (x,y) not in treated:
                    reward += 1

                    counter = 0 
                    for (dc,dr) in neighbors:
                        rn = r + dr
                        cn = c + dc
                        if rn>=0 and rn<grid_size and cn>=0 and cn<grid_size and st[rn,cn] == 0:
                            counter += 1

                    # bonus for treating a boundary fire
                    if counter >= 2:
                        reward += 4
                    #    print('treated a boundary fire')
                    #else:
                    #    print('treated a normal fire')
                        
                    treated.append((x,y))
           
        # reward for approaching center [if no fires in image]
        else:
            for k in range(len(traj)-1):
                x1, y1 = traj[k]
                x2, y2 = traj[k+1]
                if np.abs(x2-center)+np.abs(y2-center) < np.abs(x1-center)+np.abs(y1-center):
                    reward += 1.0/(len(traj)-1)
                    #print('made it closer to the center')
    
        # penalty for intersecting with 'nearest agent'
        if not set(traj).isdisjoint(other_traj):
            reward += -2*len(set(traj).intersection(other_traj))      
            #print('intersected with a friends path :(')
    
    return reward/N

test reward function with random data

In [16]:
tic = time.clock()

states = np.zeros((3,5,5)).astype(np.uint8)
states[:,2,2] = 1
trajs = []
trajs.append([(5,5),(5,5),(4,4)])
trajs.append([(3,3),(3,3),(3,3)])
trajs.append([(5,5),(4,4),(3,3)])
other_trajs = []
other_trajs.append([(1,1),(1,2),(1,1)])
other_trajs.append([(1,1),(1,2),(1,3)])
other_trajs.append([(1,1),(2,2),(3,3)])
fire_flags = [False, True, True]

reward = eelfff_reward(states, trajs, fire_flags, other_trajs)
print('minibatch reward: %0.2f' %reward)

toc = time.clock()
print("%0.2fs = %0.2fm elapsed for this test" %(toc-tic,(toc-tic)/60))

minibatch reward: 2.83
0.00s = 0.00m elapsed for this test


## Train the network

In [19]:
# simulator and network parameters
grid_size = 50
num_agents = [2,5,10]
D = []
memory_size = 1000000
dp = 0.15/0.2763
act_seq = 6
img_dim = 8
center = math.ceil(grid_size/2)
cen_var = Variable(center*torch.ones(2)).type(dtype)

# agent initialization parameters
spawn_loc = np.arange(grid_size//3//2,grid_size,grid_size//3)
perturbs = np.arange(-grid_size//3//2+1,grid_size//3//2+1,1)

# create network instance
model = eelfff_net(act_seq=act_seq, img_dim=img_dim).type(dtype)
model.train()

# optimizer and its parameters
gamma = 0.9
epsilon = 0.05
batch_size = 32
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4, weight_decay=1e-2)

# loss function
loss_fn = torch.nn.MSELoss()

In [23]:
batch_size = 64
seeds = range(1)

In [24]:
tic = time.clock()
# run simulator many times
for s in seeds:
    np.random.seed(s)
    
    # initialize simulator
    sim = FireSimulator(grid_size, rng=s)
    
    # initialize agent positions
    n = np.squeeze(np.random.choice(num_agents, 1))
    agent_pos = np.random.choice(spawn_loc, (n,2)) + np.random.choice(perturbs, (n,2))
    agent_pos = agent_pos.astype(np.int32)
    
    ep_rew = 0
        
    # run to termination
    while not sim.end:
    #for k in range(10):
        
        control = []
        new_agent_pos = np.zeros((n,2)).astype(np.int32)
        agent_data = {}
        #print(agent_pos)
        
        # generate control for each agent
        for k in range(n):
            agent_data[k] = {}
            
            # generate and save image
            img, img_st, isfire = CreateImageBW(sim.state, agent_pos[k,:])
            agent_data[k]['img'] = img

            # find nearest neighbor and their trajectory, and save it
            dists = [(np.linalg.norm(agent_pos[k,:]-pos,1),i) for i,pos in enumerate(agent_pos) if i != k]
            min_idx = min(dists)[1]
            other_img, other_img_st, other_isfire = CreateImageBW(sim.state, agent_pos[min_idx,:])
            other_traj = heuristic_trajectory(agent_pos[min_idx,:], center, act_seq, other_img_st, other_isfire)
            agent_data[k]['other_traj'] = other_traj
            
            # epsilon-greedy action choice: either random or use network
            if np.random.sample() <= epsilon:
                actions = np.random.random_integers(0, high=8, size=(act_seq,))
            else:
                img_var = Variable(torch.from_numpy(img)).type(dtype)
                other_traj_var = Variable(torch.from_numpy(np.asarray(other_traj).reshape((-1,)))).type(dtype)
                Q = model(img_var, other_traj_var, cen_var)[0]
                actions = np.argmax(Q.data.cpu().numpy(),axis=0)
                
            agent_data[k]['actions'] = actions 
            
            # generate trajectory and generate control from trajectory
            traj = actions_to_trajectory(agent_pos[k,:], actions)
            control.extend(FindGridIntersections(sim.state, traj))
            
            # calculate and store reward for agent
            reward = eelfff_reward([sim.state], [traj], [isfire], [other_traj])
            agent_data[k]['reward'] = reward
            ep_rew += reward
                        
            # store agent's new position
            new_agent_pos[k,:] = [traj[-1][0], traj[-1][1]]
            
            #print(other_traj)
            #print(actions)
            #print(traj)
            
        # remove duplicates from control sequence
        control = list(set(control))
        #if control:
        #    print('control is not empty')
        #    print(control)
        #    5/0
        
        # step simulator
        sim.step(control, dbeta=dp)
        
        # update agent position
        agent_pos = new_agent_pos
        
        # grab new state information and add to replay memory
        isterminal = False
        for k in range(n):
            # generate and save image
            img, img_st, isfire = CreateImageBW(sim.state, agent_pos[k,:])
            agent_data[k]['next_img'] = img
            
            # find nearest neighbor and their trajectory
            dists = [(np.linalg.norm(agent_pos[k,:]-pos,1),i) for i,pos in enumerate(agent_pos) if i != k]
            min_idx = min(dists)[1]
            other_img, other_img_st, other_isfire = CreateImageBW(sim.state, agent_pos[min_idx,:])
            other_traj = heuristic_trajectory(agent_pos[min_idx,:], center, act_seq, other_img_st, other_isfire)
            agent_data[k]['next_other_traj'] = other_traj
        
            # check for terminal state
            if sim.end:
                isterminal = True
                
            D.append((agent_data[k]['img'],agent_data[k]['other_traj'],agent_data[k]['actions'],
                      agent_data[k]['reward'],agent_data[k]['next_img'],
                      agent_data[k]['next_other_traj'],isterminal))
                
        # create minibatch from replay memory
        loss = 0
        if len(D) <= batch_size:
            batch = D            
        else:
            batch = []
            idxs = np.random.random_integers(0,high=len(D)-1,size=batch_size)
            for k in range(batch_size):
                batch.append(D[idxs[k]])

        # calculate loss over batch
        # exp indices: 0-img, 1-other_traj, 2-actions, 3-reward, 4-next_img, 5-next_other_traj
        for exp in batch:
            isterminal = exp[-1]
            tt = Variable(exp[3]*torch.ones(1), requires_grad=False).type(dtype)
            
            img_var = Variable(torch.from_numpy(exp[0])).type(dtype)
            other_traj_var = Variable(torch.from_numpy(np.asarray(exp[1]).reshape((-1,)))).type(dtype)
            Q = model(img_var, other_traj_var, cen_var)[0]
            x = Q[torch.from_numpy(exp[2]).type(torch.cuda.LongTensor)].diag().mean()
            
            if not isterminal:
                next_img_var = Variable(torch.from_numpy(exp[4])).type(dtype)
                next_other_traj_var = Variable(torch.from_numpy(np.asarray(exp[5]).reshape((-1,)).astype(np.int32))).type(dtype)

                Q = model(next_img_var, next_other_traj_var, cen_var)[0]
                maxQ = Q.max(dim=0)[0].mean()
                x += gamma*maxQ
            
            #if isterminal:
            #    tt = exp[3]
            #else:
            #    next_img_var = Variable(torch.from_numpy(exp[4])).type(dtype)
            #    next_other_traj_var = Variable(torch.from_numpy(np.asarray(exp[5]).reshape((-1,)).astype(np.int32))).type(dtype)

                #Q = model(next_img_var, next_other_traj_var)[0]
                #maxQ = Q.max(dim=0)[0].mean()
                #Q = model(next_img_var, next_other_traj_var)[0].data.cpu().numpy()
                #maxQ = np.mean(np.amax(Q, axis=0))
                #tt = exp[3] + gamma*maxQ

            #tt = Variable(tt*torch.ones(1), requires_grad=False).type(dtype)

            #img_var = Variable(torch.from_numpy(exp[0])).type(dtype)
            #other_traj_var = Variable(torch.from_numpy(np.asarray(exp[1]).reshape((-1,)))).type(dtype)
            #Q = model(img_var, other_traj_var)[0]
            #x = Q[torch.from_numpy(exp[2]).type(torch.cuda.LongTensor)].diag().mean()
            
            loss += loss_fn(x,tt)

        loss /= batch_size

        # update network
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # drop from memory if too many elements
        if len(D) > memory_size:
            D = D[len(D)-memory_size:]
            
        #print(agent_pos)
        #print()
        #5/0
            
    print("average reward: %0.2f" %(ep_rew/(n*sim.iter)))
    print("episode stats: %s, %f" %(sim.stats,sim.stats[0]/np.sum(sim.stats)))
        
toc = time.clock()
print("%0.2fs = %0.2fm elapsed" %(toc-tic,(toc-tic)/60))

average reward: 0.30
episode stats: [  10    0 2490], 0.004000
36.70s = 0.61m elapsed


In [22]:
Q

Variable containing:
 -6.8247  20.1575   8.8880  31.1630  37.0713  26.3245
-23.2858 -29.1566  24.4951 -45.2419  12.9220  -4.5020
-22.3807  13.6333   3.5209  -7.8777 -65.7601 -47.6881
 30.7718 -18.9351  60.4584  -5.4864   8.7071   4.5670
 20.7725 -20.1552  -5.8310  44.2544  -7.9679  25.6896
 24.4845   3.1176  -7.3361  24.4351 -10.0821 -22.8522
 19.4358  20.0006  -7.9166  48.3236   2.1340 -24.1157
-22.9261 -46.3666   6.8603 -16.0953 -10.8690 -37.7651
 53.6163  27.3654  28.5166  14.5562   9.0042  68.6231
[torch.cuda.FloatTensor of size 9x6 (GPU 0)]

In [57]:
traj

[(39, -1), (38, 0), (39, 0), (39, 0), (39, 0), (39, 1), (38, 2)]

In [58]:
other_traj

[(38, -3), (37, -2), (36, -1), (35, 0), (34, 1), (33, 2), (32, 3)]

In [41]:
type(exp[5][0][1])

numpy.int32

In [28]:
D[100]

(array([[  0,   0,   0,   0, 128,   0,   0,   0],
        [  0,   0,   0,   0,   0, 128,   0,   0],
        [  0,   0,   0, 128,   0,   0, 128, 128],
        [  0,   0,   0,   0,   0, 128,   0,   0],
        [  0,   0,   0,   0,   0, 128, 128,   0],
        [  0, 128, 128,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0, 128,   0, 128],
        [  0,   0,   0,   0,   0,   0, 128, 128]], dtype=uint8),
 [(47, 32), (46, 33), (47, 33), (48, 33), (48, 34), (49, 34), (49, 33)],
 array([4, 5, 5, 8, 7, 3]),
 2.0,
 array([[  0,   0,   0,   0,   0, 128,   0, 128],
        [  0,   0,   0, 128,   0,   0,   0, 128],
        [  0,   0,   0,   0, 128,   0,   0, 128],
        [  0,   0, 128,   0,   0, 128, 128,   0],
        [  0,   0,   0,   0, 128,   0,   0,   0],
        [  0,   0,   0,   0,   0, 128,   0,   0],
        [128, 128,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0, 128,   0, 128,   0]], dtype=uint8),
 [(47, 31), (46, 32), (46, 33), (47, 34), (47, 35), (48, 34), (

In [87]:
type(np.asarray(other_traj)[0][0])

numpy.int64

In [82]:
type(np.asarray(exp[5])[0][0])

numpy.int8

In [75]:
type(exp[5][0][1])

numpy.int8

In [65]:
type(traj[0][0])

numpy.int32

In [64]:
torch.cuda.FloatTensor(traj)

RuntimeError: tried to construct a tensor from a nested float sequence, but found an item of type numpy.int32 at index (0, 0)

In [54]:
np.asarray(exp[5])

array([[15, 11],
       [15, 11],
       [15, 11],
       [15, 11],
       [15, 11],
       [15, 11],
       [15, 11]], dtype=int8)

In [49]:
np.asarray(other_traj).reshape((-1,))

array([15, 11, 15, 11, 15, 11, 15, 11, 15, 11, 15, 11, 15, 11], dtype=int8)

In [45]:
other_traj

[(15, 11), (15, 11), (15, 11), (15, 11), (15, 11), (15, 11), (15, 11)]

In [36]:
agent_pos.astype(np.int8)

array([[26, 25],
       [ 6, 16],
       [29,  6],
       [32, 39],
       [13, 20],
       [27, 34],
       [40, 20],
       [ 2, 34],
       [13,  7],
       [ 6, 44]], dtype=int8)

In [28]:
control

[]

In [29]:
len(D)

10000

In [ ]:
exp[2]

In [ ]:
Q[torch.from_numpy(exp[2]).type(torch.cuda.LongTensor)]

In [ ]:
Q[torch.from_numpy(exp[2]).type(torch.cuda.LongTensor)].diag()

In [18]:
torch.randn(2)


-0.2368
-1.5721
[torch.FloatTensor of size 2]